feat: BIKDARTEM-171: [FRONTEND] Реализовать компоненты таблицы в разд…
martirdev/martir pull request #16
Opened 2023-07-31 14:58 UTC by AnnaErs

…еле shared

2023-07-31 15:14 UTC, mimpushkarev commented on package.json
> +    "swr": "^2.1.2",
Че?

2023-08-01 09:58 UTC, AnnaErs commented on package.json
> +    "swr": "^2.1.2",
Хз)

2023-08-01 12:23 UTC, mimpushkarev requested changes

2023-08-02 12:57 UTC, mimpushkarev commented on src/pages/releases/Releases.tsx
> +  return <Container className="">
Пустой класснейм, нужно правило в линтере добавить, чтобы он на такие вещи жаловался

2023-08-02 13:00 UTC, merged